version: '3.7'
services:
    application:
        container_name: test_tools_app
        image: richcongress/php:7.3-fpm
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
